---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    postgres_password: "TestPass123"

  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-17-jdk
          - nginx
          - postgresql
          - git
          - maven
          - nodejs
          - npm
          - zip
        update_cache: yes
        state: present
      register: apt_result
      until: apt_result is succeeded
      retries: 3
      delay: 10

    - name: Set password for postgres user
      shell: |
        sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ postgres_password }}';"
      changed_when: False

    - name: Configure PostgreSQL for password authentication
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer$'
        line: 'local   all             postgres                                md5'
        state: present

    - name: Restart PostgreSQL service to apply authentication changes
      service:
        name: postgresql
        state: restarted

    - name: Create testdb database
      shell: |
        PGPASSWORD="{{ postgres_password }}" psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'testdb'" | grep -q 1 || PGPASSWORD="{{ postgres_password }}" psql -h localhost -U postgres -c "CREATE DATABASE testdb;"
      environment:
        PGPASSWORD: "{{ postgres_password }}"
      ignore_errors: yes

    - name: Grant privileges on testdb to postgres user
      shell: |
        PGPASSWORD="{{ postgres_password }}" psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO postgres;"
      environment:
        PGPASSWORD: "{{ postgres_password }}"
      ignore_errors: yes

    - name: Clone Spring Boot app from GitHub
      git:
        repo: 'https://github.com/namdeopawar/Simple-SpringBoot-ReactApp.git'
        dest: /opt/SpringBootReactApp
        version: main

    - name: Run the Spring Boot application
      shell: |
        java -jar /opt/SpringBootReactApp/artifacts/myapp*.jar &
      async: 10
      poll: 0

    - name: Unzip frontend.zip to /var/www/html/myweb/
      unarchive:
        src: /opt/SpringBootReactApp/artifacts/frontend.zip
        dest: /var/www/html/myweb/
        remote_src: yes

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
