---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-17-jdk
          - nginx
          - postgresql
          - git
          - maven
          - nodejs
          - npm
          - zip
        update_cache: yes
        state: present
      register: apt_result
      until: apt_result is succeeded
      retries: 3
      delay: 10

    - name: Configure PostgreSQL for password authentication
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres\s+peer$'
        line: 'local   all             postgres                                md5'
        state: present

    - name: Restart PostgreSQL service to apply authentication changes
      service:
        name: postgresql
        state: restarted

    - name: Create PostgreSQL database and user
      shell: |
        sudo -u postgres /usr/bin/psql -tc "SELECT 1 FROM pg_database WHERE datname = 'testdb'" | grep -q 1 || sudo -u postgres /usr/bin/psql -c "CREATE DATABASE testdb;"
        sudo -u postgres /usr/bin/psql -tc "SELECT 1 FROM pg_roles WHERE rolname = 'testuser'" | grep -q 1 || sudo -u postgres /usr/bin/psql -c "CREATE USER testuser WITH PASSWORD 'TestPass123';"
        sudo -u postgres /usr/bin/psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;"
      ignore_errors: yes

    - name: Add PostgreSQL user authentication method
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: "local   all             testuser                                md5"
        state: present

    - name: Restart PostgreSQL to apply new user configuration
      service:
        name: postgresql
        state: restarted

    - name: Clone Spring Boot app from GitHub
      git:
        repo: 'https://github.com/namdeopawar/Simple-SpringBoot-ReactApp.git'
        dest: /opt/SpringBootReactApp
        version: main

    - name: Run the Spring Boot application
      shell: |
        java -jar /opt/SpringBootReactApp/artifacts/myapp*.jar &
      async: 10
      poll: 0

    - name: Unzip frontend.zip to /var/www/html/myweb/
      unarchive:
        src: /opt/SpringBootReactApp/artifacts/frontend.zip
        dest: /var/www/html
        remote_src: yes

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
